// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlDh74-HThh7yu9p74xLHlreIwp27nQY4',
    appId: '1:298670393818:web:762d28a065a209ddc318e3',
    messagingSenderId: '298670393818',
    projectId: 'smartparking-79613',
    authDomain: 'smartparking-79613.firebaseapp.com',
    storageBucket: 'smartparking-79613.appspot.com',
    measurementId: 'G-9CWC7VGKRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBSf3WMZrelNYH3gXrUg1XPmENrsAafFA',
    appId: '1:298670393818:android:5854d75440a773d4c318e3',
    messagingSenderId: '298670393818',
    projectId: 'smartparking-79613',
    storageBucket: 'smartparking-79613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTAapHpS6ujwHeXTRUuEqgUW9MYfw-g-k',
    appId: '1:298670393818:ios:71e1fa13b6ede27fc318e3',
    messagingSenderId: '298670393818',
    projectId: 'smartparking-79613',
    storageBucket: 'smartparking-79613.appspot.com',
    iosBundleId: 'com.KMEC.smartparking',
  );
}
